### ISSUE TITLE
3. MyVehicle - AutoPilot (lap time)

### ISSUE THREAD

**Issue by goncaloacteixeira** [skdGT/feup-cgra#10]
O Dirigível demora mais de 5 segundos a completar uma volta em modo de piloto automático.

**Comment by Ca-moes** [comment]
![image](https://user-images.githubusercontent.com/54408098/80231206-f5565880-864a-11ea-837c-4cae0ce77617.png)

Deixar aqui inspiração

**Comment by goncaloacteixeira** [comment]
Esse lastUpdate era uma variavel definida no construtor de Scene?
