### ISSUE TITLE
Terreno - Alteração de Alturas

### ISSUE THREAD

**Issue by goncaloacteixeira** [skdGT/feup-cgra#14]
Modifique a textura de alturas (usando um editor de imagem) de forma a que haja uma
zona central plana de dimensões aproximadas de 20x20 unidades (altura a zero, Y=0).

Em alternativa, poderá substituir as texturas fornecidas por outro par de texturas de cor
e altura para o efeito - mas que terá de ter a zona central plana como descrito.
Na classe MyScene, altere o código de forma a que:
- Se necessário, para alinhar as imagens do cubemap com o terreno, aplicar translação
em Y no terreno ou no cubo;
- A posição e orientação inicial da câmara permita ver o dirigível e a maior parte da zona
plana do terreno.
Capture uma perspetiva da cena contendo o ambiente de fundo criado com o cubemap, o
terreno, e o veículo. (2)

**Comment by Ca-moes** [comment]
![image](https://user-images.githubusercontent.com/54408098/80278965-643abc80-86f2-11ea-83a3-1cc0a032e050.png)

![image](https://user-images.githubusercontent.com/54408098/80279060-0490e100-86f3-11ea-9b74-2d9f8a3b6e8f.png)

![image](https://user-images.githubusercontent.com/54408098/80281168-327d2200-8701-11ea-97d0-050821149a68.png)
