### ISSUE TITLE
3. MyVehicle - Lemes

### ISSUE THREAD

**Issue by goncaloacteixeira** [skdGT/feup-cgra#3]
Lemes

**Comment by Ca-moes** [comment]
![image](https://user-images.githubusercontent.com/54408098/80088826-f016e200-8554-11ea-92c8-6a9eedc30895.png)
Fiz o MyRudder com estas posições iniciais (no eixo y, -z) para ser mais fácil fazer a parte animada, menos uma transformação de rotação
