### ISSUE TITLE
Screenshot Cenário (terreno)

### ISSUE THREAD

**Issue by goncaloacteixeira** [skdGT/feup-cgra#32]
*Capture uma perspetiva da cena contendo o ambiente de fundo criado com o cubemap, o
terreno, e o veículo.* (2)

**Comment by skdGT** [comment]
![image](https://user-images.githubusercontent.com/52114623/80282485-b6d3a300-8709-11ea-8290-0a443ef3e014.png)

**Comment by goncaloacteixeira** [comment]
![image](https://user-images.githubusercontent.com/54408098/82726237-8e27d480-9cda-11ea-8199-f52bdfa73875.png)
![image](https://user-images.githubusercontent.com/52114623/80282633-6f99e200-870a-11ea-8b23-cd5dbb283298.png)
