### ISSUE TITLE
3. MyVehicle - AutoPilot

### ISSUE THREAD

**Issue by goncaloacteixeira** [skdGT/feup-cgra#4]
Piloto automático

**Comment by Ca-moes** [comment]
> Uma volta completa deve demorar 5 segundos, independentemente do
desempenho do computador usado.

Dúvida: No meu pc uma volta demora mais do que 5 segundos. Checkaste isso ou é do meu pc?

**Comment by goncaloacteixeira** [comment]
> > Uma volta completa deve demorar 5 segundos, independentemente do
> > desempenho do computador usado.
> 
> Dúvida: No meu pc uma volta demora mais do que 5 segundos. Checkaste isso ou é do meu pc?

Que estranho, quanto tempo demora no teu pc?
