### ISSUE TITLE
6.1 - Bandeira

### ISSUE THREAD

**Issue by Ca-moes** [skdGT/feup-cgra#44]
Adicione um objeto da classe MyPlane à classe MyVehicle, e coloque-o atrás do corpo do
dirigível, semelhante ao exemplo na Figura 8. Crie e inicialize shaders em MyVehicle que
serão aplicados ao novo objeto bandeira, que deverão:
- Alterar a altura dos vértices do plano de forma a recriar um efeito de “ondulação” no
objeto, seguindo uma função sinusoidal (Sugestão: use as coordenadas de textura
como parâmetro);
- O efeito de ondulação deverá ser animado, e a velocidade da animação deverá
depender da velocidade do dirigível;
- Aplique uma textura à escolha com o fragment shader.

![image](https://user-images.githubusercontent.com/54408098/80287034-0c6a7880-8727-11ea-9a04-66e1145237e1.png)

Capture uma imagem que demonstre o dirigível com a bandeira criada, em que seja possível
observar a ondulação na mesma

**Comment by goncaloacteixeira** [comment]
Falta aqui a imagem da flag quando estiver pronta.

**Comment by Ca-moes** [comment]
![image](https://user-images.githubusercontent.com/54408098/82726313-2aea7200-9cdb-11ea-8e12-30b5dc5ac4d9.png)
![image](https://user-images.githubusercontent.com/54408098/82726310-21610a00-9cdb-11ea-8991-75cadfc597fd.png)

**Comment by skdGT** [comment]
Consegues que se veja melhor a ondulação da flag?

**Comment by goncaloacteixeira** [comment]
se calhar é melhor atualizar esta imagem @Ca-moes
