### ISSUE TITLE
6.2. Contador de mantimentos entregues

### ISSUE THREAD

**Issue by Ca-moes** [skdGT/feup-cgra#45]
Crie uma nova classe MyBillboard, para representar um mostrador com o número de
mantimentos (MySupply) lançados, tal como contabilizado pela variável nSuppliesDelivered.
Este mostrador deverá ser constituído por (ver figura 9, dimensões indicativas):
- um plano de base com uma textura decorativa que inclua o texto “Supplies Delivered”
- Uma barra de progresso (detalhes abaixo)
- duas traves que suportam a geometria acima.

![image](https://user-images.githubusercontent.com/54408098/80287008-d75e2600-8726-11ea-9360-51a9b2461344.png)

O plano de base deve ter dimensões 2 x 1 unidades, as traves devem ter altura de uma
unidade, e o mostrador deve ser colocado no terreno numa posição bem visível no ponto de
vista inicial da câmara.
A barra de progresso deve ser constituída por um único plano de dimensões 1.5 x 0.2 unidades
(largura x altura) associado a um par de shaders desenvolvido especificamente para o efeito e
ativado na classe MyBillboard, obedecendo ao seguinte (ver figura 10):
- Quando a barra está totalmente preenchida (ou seja, todos os mantimentos entregues)
deve ter o aspeto de um gradiente horizontal que varie de vermelho (RGB = 1,0,0) para
verde (RGB = 0,1,0). Este gradiente deve ser calculado no fragment shader;
- Quando apenas uma parte dos mantimentos tiver sido entregue, só deve ser visível a
percentagem correspondente do gradiente. Por exemplo, quatro mantimentos entregues
num total de cinco corresponderá a 80% do gradiente total;
- A restante área deve ser preenchida com uma cor constante à escolha, desde que
contraste com os tons do gradiente (no exemplo, cinzento RGB = 0.5,0.5,0.5).

Capture uma imagem do mostrador quando três mantimentos tiverem sido lançados. (6)
Submeta o código final. (1)

![image](https://user-images.githubusercontent.com/54408098/80287021-efce4080-8726-11ea-9fac-690cd413c1ed.png)

**Comment by goncaloacteixeira** [comment]
![image](https://user-images.githubusercontent.com/54408098/82582351-d388bc80-9b89-11ea-812c-a9e57c14cba3.png)
3 Supplies lançados
![image](https://user-images.githubusercontent.com/52114623/80291527-1fd90c00-8746-11ea-8136-0a4b6d99d1b4.png)
