### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by Ca-moes** [skdGT/feup-cgra#46]
1. A modelação do blimp tem de ser feita em MyVehicle ou pode ser feita numa class à parte (e.g. MyBody) e MyVehicle usa uma instância dessa?
2. Qual é o tempo mínimo entre drops de supplies?
3. Vai ser testado o tempo que demora a fazer uma rotação e o tempo que demora a cair o supply, também será testado o tempo de rotação do blimp sobre si mesmo?
4. Shaders de Terreno têm de ser usados em MyTerrain ou podem ser usados em MyScene?

^ Já mandei por PM estas dúvidas ao stor, quando ele responder aviso: ^
![image](https://user-images.githubusercontent.com/54408098/80311431-865a3a80-87d7-11ea-9d0d-307dd60446c4.png)

5. Enunciado : 
> O efeito de ondulação deverá ser animado, e a velocidade da animação deverá
depender da velocidade do dirigível;

Estado o dirigivel parado é suposto não ter animação?

**Comment by Ca-moes** [comment]
Respostas: 
1. pode ser à parte e o vehicle usar uma instância
2. não especificamos, fica ao vosso critério (se é que querem colocar limite)
3. Não vamos "testar" propriamente dito. Esperamos é que seja fluído.
4. o ideal é serem encapsulados no terreno.

**Comment by goncaloacteixeira** [comment]
@Ca-moes 
Então parece-me que temos tudo em conformidade, no que diz respeito a esses pontos.

**Comment by Ca-moes** [comment]
![image](https://user-images.githubusercontent.com/54408098/81170011-cbc5f700-8f91-11ea-97e4-f926ad3113ee.png)
