### ISSUE TITLE
Código para Submissão

### ISSUE THREAD

**Issue by goncaloacteixeira** [skdGT/feup-cgra#58]
Zips do código para submissão.

**Comment by Ca-moes** [comment]
![image](https://user-images.githubusercontent.com/54408098/82580509-1d23d800-9b87-11ea-9744-229fc5a9ecb2.png)
![image](https://user-images.githubusercontent.com/54408098/82580305-e483fe80-9b86-11ea-8396-047e1def5ca8.png)
![image](https://user-images.githubusercontent.com/54408098/82580343-ee0d6680-9b86-11ea-9a5c-a2d21f239532.png)
![image](https://user-images.githubusercontent.com/54408098/82580376-f5cd0b00-9b86-11ea-9f24-6b1da911c1fd.png)
![image](https://user-images.githubusercontent.com/54408098/82580421-01203680-9b87-11ea-9191-d1de61784dba.png)
![image](https://user-images.githubusercontent.com/54408098/82580462-08dfdb00-9b87-11ea-98bd-e5d63a63b780.png)

**Comment by goncaloacteixeira** [comment]
as imagens estão nos Issues marcados com #submission
