### ISSUE TITLE
Progressão da bandeira

### ISSUE THREAD

**Issue by Ca-moes** [skdGT/feup-cgra#61]
A bandeira tem movimento ondulatório mas esse movimento tem de se propagar pela bandeira e não ser estático

![](https://www.mushi-san.com/geladeira/2010/06/25/portugal.gif)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/54408098/80750181-8b90ef80-8b1f-11ea-8112-caa783621de3.gif)

**Comment by goncaloacteixeira** [comment]
Pois, bem me parecia, tem de fazer um movimento de ondulação ne? Eu já vi alguns shaders assim nos foruns de WebGL
