### ISSUE TITLE
AutoPilot Reset

### ISSUE THREAD

**Issue by Ca-moes** [skdGT/feup-cgra#68]
![image](https://user-images.githubusercontent.com/54408098/82642079-408d6800-9c05-11ea-9f87-1444e6f29bac.png)
![image](https://user-images.githubusercontent.com/54408098/82642127-5b5fdc80-9c05-11ea-90cc-dbcbea659e31.png)

Em autopilot:
- [x] ao clicar R tem de dar reset a tudo
- [x] ao clicar P tem que voltar ao estado normal

**Comment by goncaloacteixeira** [comment]
Então digamos que quando tocamos de novo no `P` é suposto parar o piloto automático e o blimp fica no sítio onde está, é isso certo? @Ca-moes
